//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from KotlinVar.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="KotlinVarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public interface IKotlinVarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinVarParser.startRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStartRule([NotNull] KotlinVarParser.StartRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinVarParser.startRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStartRule([NotNull] KotlinVarParser.StartRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinVarParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterId([NotNull] KotlinVarParser.IdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinVarParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitId([NotNull] KotlinVarParser.IdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinVarParser.string_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString_literal([NotNull] KotlinVarParser.String_literalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinVarParser.string_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString_literal([NotNull] KotlinVarParser.String_literalContext context);
}
