//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from KotlinVar.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public partial class KotlinVarLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		CONST_KW=1, VAL_KW=2, EQUAL=3, SEMI=4, ID=5, STRING=6, WS=7;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"CONST_KW", "VAL_KW", "EQUAL", "SEMI", "ID", "STRING", "LETTER", "DIGIT", 
		"SYMBOL", "WS"
	};


	public KotlinVarLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public KotlinVarLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'const'", "'val'", "'='", "';'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "CONST_KW", "VAL_KW", "EQUAL", "SEMI", "ID", "STRING", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "KotlinVar.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static KotlinVarLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\t', '\x44', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\a', '\x6', '*', '\n', 
		'\x6', '\f', '\x6', '\xE', '\x6', '-', '\v', '\x6', '\x3', '\a', '\x3', 
		'\a', '\a', '\a', '\x31', '\n', '\a', '\f', '\a', '\xE', '\a', '\x34', 
		'\v', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', 
		'\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x6', '\v', 
		'?', '\n', '\v', '\r', '\v', '\xE', '\v', '@', '\x3', '\v', '\x3', '\v', 
		'\x2', '\x2', '\f', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', 
		'\v', '\a', '\r', '\b', '\xF', '\x2', '\x11', '\x2', '\x13', '\x2', '\x15', 
		'\t', '\x3', '\x2', '\x6', '\x4', '\x2', '\x43', '\\', '\x63', '|', '\x3', 
		'\x2', '\x32', ';', '\n', '\x2', '*', '-', '/', '/', '\x31', ';', '=', 
		'=', '\x43', '\\', '\x61', '\x61', '\x63', '}', '\x7F', '\x7F', '\x5', 
		'\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', '\x2', '\x45', '\x2', '\x3', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x3', '\x17', 
		'\x3', '\x2', '\x2', '\x2', '\x5', '\x1D', '\x3', '\x2', '\x2', '\x2', 
		'\a', '!', '\x3', '\x2', '\x2', '\x2', '\t', '#', '\x3', '\x2', '\x2', 
		'\x2', '\v', '%', '\x3', '\x2', '\x2', '\x2', '\r', '.', '\x3', '\x2', 
		'\x2', '\x2', '\xF', '\x37', '\x3', '\x2', '\x2', '\x2', '\x11', '\x39', 
		'\x3', '\x2', '\x2', '\x2', '\x13', ';', '\x3', '\x2', '\x2', '\x2', '\x15', 
		'>', '\x3', '\x2', '\x2', '\x2', '\x17', '\x18', '\a', '\x65', '\x2', 
		'\x2', '\x18', '\x19', '\a', 'q', '\x2', '\x2', '\x19', '\x1A', '\a', 
		'p', '\x2', '\x2', '\x1A', '\x1B', '\a', 'u', '\x2', '\x2', '\x1B', '\x1C', 
		'\a', 'v', '\x2', '\x2', '\x1C', '\x4', '\x3', '\x2', '\x2', '\x2', '\x1D', 
		'\x1E', '\a', 'x', '\x2', '\x2', '\x1E', '\x1F', '\a', '\x63', '\x2', 
		'\x2', '\x1F', ' ', '\a', 'n', '\x2', '\x2', ' ', '\x6', '\x3', '\x2', 
		'\x2', '\x2', '!', '\"', '\a', '?', '\x2', '\x2', '\"', '\b', '\x3', '\x2', 
		'\x2', '\x2', '#', '$', '\a', '=', '\x2', '\x2', '$', '\n', '\x3', '\x2', 
		'\x2', '\x2', '%', '+', '\x5', '\xF', '\b', '\x2', '&', '*', '\x5', '\xF', 
		'\b', '\x2', '\'', '*', '\x5', '\x11', '\t', '\x2', '(', '*', '\a', '\x61', 
		'\x2', '\x2', ')', '&', '\x3', '\x2', '\x2', '\x2', ')', '\'', '\x3', 
		'\x2', '\x2', '\x2', ')', '(', '\x3', '\x2', '\x2', '\x2', '*', '-', '\x3', 
		'\x2', '\x2', '\x2', '+', ')', '\x3', '\x2', '\x2', '\x2', '+', ',', '\x3', 
		'\x2', '\x2', '\x2', ',', '\f', '\x3', '\x2', '\x2', '\x2', '-', '+', 
		'\x3', '\x2', '\x2', '\x2', '.', '\x32', '\a', '$', '\x2', '\x2', '/', 
		'\x31', '\x5', '\x13', '\n', '\x2', '\x30', '/', '\x3', '\x2', '\x2', 
		'\x2', '\x31', '\x34', '\x3', '\x2', '\x2', '\x2', '\x32', '\x30', '\x3', 
		'\x2', '\x2', '\x2', '\x32', '\x33', '\x3', '\x2', '\x2', '\x2', '\x33', 
		'\x35', '\x3', '\x2', '\x2', '\x2', '\x34', '\x32', '\x3', '\x2', '\x2', 
		'\x2', '\x35', '\x36', '\a', '$', '\x2', '\x2', '\x36', '\xE', '\x3', 
		'\x2', '\x2', '\x2', '\x37', '\x38', '\t', '\x2', '\x2', '\x2', '\x38', 
		'\x10', '\x3', '\x2', '\x2', '\x2', '\x39', ':', '\t', '\x3', '\x2', '\x2', 
		':', '\x12', '\x3', '\x2', '\x2', '\x2', ';', '<', '\t', '\x4', '\x2', 
		'\x2', '<', '\x14', '\x3', '\x2', '\x2', '\x2', '=', '?', '\t', '\x5', 
		'\x2', '\x2', '>', '=', '\x3', '\x2', '\x2', '\x2', '?', '@', '\x3', '\x2', 
		'\x2', '\x2', '@', '>', '\x3', '\x2', '\x2', '\x2', '@', '\x41', '\x3', 
		'\x2', '\x2', '\x2', '\x41', '\x42', '\x3', '\x2', '\x2', '\x2', '\x42', 
		'\x43', '\b', '\v', '\x2', '\x2', '\x43', '\x16', '\x3', '\x2', '\x2', 
		'\x2', '\a', '\x2', ')', '+', '\x32', '@', '\x3', '\x2', '\x3', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
