//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comp_Lab1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Label_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Label_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Comp_Lab1.Label.en", typeof(Label_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Editor / Language Processor
        ///Version 1.0
        ///Developer: Pavel Obelenets.
        /// </summary>
        internal static string AboutMsg {
            get {
                return ResourceManager.GetString("AboutMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Editor / Language Processor
        ///Version 1.0
        ///Developer: Pavel Ovelenets.
        /// </summary>
        internal static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total error count: {0}.
        /// </summary>
        internal static string AnalysisErrorCount {
            get {
                return ResourceManager.GetString("AnalysisErrorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax analysis: No errors found..
        /// </summary>
        internal static string AnalysisNoErrors {
            get {
                return ResourceManager.GetString("AnalysisNoErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis completed successfully. No errors found!.
        /// </summary>
        internal static string AnalysisSuccess {
            get {
                return ResourceManager.GetString("AnalysisSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiler.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string colCode {
            get {
                return ResourceManager.GetString("colCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string ColFile {
            get {
                return ResourceManager.GetString("ColFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid fragment.
        /// </summary>
        internal static string colFragment {
            get {
                return ResourceManager.GetString("colFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string ColLine {
            get {
                return ResourceManager.GetString("ColLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ColMessage {
            get {
                return ResourceManager.GetString("ColMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string colPos {
            get {
                return ResourceManager.GetString("colPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Type.
        /// </summary>
        internal static string colType {
            get {
                return ResourceManager.GetString("colType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: empty text..
        /// </summary>
        internal static string ErrEmptyInput {
            get {
                return ResourceManager.GetString("ErrEmptyInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter code for analysis..
        /// </summary>
        internal static string ErrEmptyMsg {
            get {
                return ResourceManager.GetString("ErrEmptyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: empty text..
        /// </summary>
        internal static string ErrEmptyStatus {
            get {
                return ResourceManager.GetString("ErrEmptyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty input.
        /// </summary>
        internal static string ErrEmptyTitle {
            get {
                return ResourceManager.GetString("ErrEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword expected..
        /// </summary>
        internal static string ErrExpectedKeyword {
            get {
                return ResourceManager.GetString("ErrExpectedKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra element &apos;{0}&apos; before &apos;{1}&apos;.
        /// </summary>
        internal static string ErrExtraElement {
            get {
                return ResourceManager.GetString("ErrExtraElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found!
        ///Check if it is copied to: {0}.
        /// </summary>
        internal static string ErrFileNotFound {
            get {
                return ResourceManager.GetString("ErrFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        internal static string ErrFileRead {
            get {
                return ResourceManager.GetString("ErrFileRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lexical error: {0} &apos;{1}&apos;.
        /// </summary>
        internal static string ErrLexical {
            get {
                return ResourceManager.GetString("ErrLexical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required element: &apos;{0}&apos;.
        /// </summary>
        internal static string ErrMissingElement {
            get {
                return ResourceManager.GetString("ErrMissingElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: no open tabs..
        /// </summary>
        internal static string ErrNoTabs {
            get {
                return ResourceManager.GetString("ErrNoTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please create or open a file for analysis first..
        /// </summary>
        internal static string ErrNoTabsMsg {
            get {
                return ResourceManager.GetString("ErrNoTabsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: no open tabs..
        /// </summary>
        internal static string ErrNoTabsStatus {
            get {
                return ResourceManager.GetString("ErrNoTabsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab not found.
        /// </summary>
        internal static string ErrNoTabsTitle {
            get {
                return ResourceManager.GetString("ErrNoTabsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open page: {0}.
        /// </summary>
        internal static string ErrOpenPage {
            get {
                return ResourceManager.GetString("ErrOpenPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open page: .
        /// </summary>
        internal static string ErrOpenPage1 {
            get {
                return ResourceManager.GetString("ErrOpenPage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to line {0}, pos {1}.
        /// </summary>
        internal static string ErrorLocationFormat {
            get {
                return ResourceManager.GetString("ErrorLocationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        internal static string ErrPrefix {
            get {
                return ResourceManager.GetString("ErrPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of file. Missing: &apos;{0}&apos;.
        /// </summary>
        internal static string ErrUnexpectedEOF {
            get {
                return ResourceManager.GetString("ErrUnexpectedEOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to file {0}?.
        /// </summary>
        internal static string ExitConfirm {
            get {
                return ResourceManager.GetString("ExitConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitTitle {
            get {
                return ResourceManager.GetString("ExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found!
        ///Check path: {0}.
        /// </summary>
        internal static string FileNotFoundMsg {
            get {
                return ResourceManager.GetString("FileNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved successfully..
        /// </summary>
        internal static string FileSaved {
            get {
                return ResourceManager.GetString("FileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to line {0}, pos {1}.
        /// </summary>
        internal static string GridLocation {
            get {
                return ResourceManager.GetString("GridLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LangEn {
            get {
                return ResourceManager.GetString("LangEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string LangRu {
            get {
                return ResourceManager.GetString("LangRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grammar Classification.
        /// </summary>
        internal static string MenuClass {
            get {
                return ResourceManager.GetString("MenuClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string MenuCopy {
            get {
                return ResourceManager.GetString("MenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string MenuCreate {
            get {
                return ResourceManager.GetString("MenuCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string MenuCut {
            get {
                return ResourceManager.GetString("MenuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string MenuDelete {
            get {
                return ResourceManager.GetString("MenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        internal static string MenuDocs {
            get {
                return ResourceManager.GetString("MenuDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Example.
        /// </summary>
        internal static string MenuExample {
            get {
                return ResourceManager.GetString("MenuExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grammar.
        /// </summary>
        internal static string MenuGrammar {
            get {
                return ResourceManager.GetString("MenuGrammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string MenuHelpRoot {
            get {
                return ResourceManager.GetString("MenuHelpRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string MenuLangRoot {
            get {
                return ResourceManager.GetString("MenuLangRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis Method.
        /// </summary>
        internal static string MenuMethod {
            get {
                return ResourceManager.GetString("MenuMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string MenuPaste {
            get {
                return ResourceManager.GetString("MenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string MenuRedo {
            get {
                return ResourceManager.GetString("MenuRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string MenuRun {
            get {
                return ResourceManager.GetString("MenuRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string MenuSave {
            get {
                return ResourceManager.GetString("MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string MenuSaveAs {
            get {
                return ResourceManager.GetString("MenuSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string MenuSelectAll {
            get {
                return ResourceManager.GetString("MenuSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Help.
        /// </summary>
        internal static string MenuShowHelp {
            get {
                return ResourceManager.GetString("MenuShowHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code.
        /// </summary>
        internal static string MenuSource {
            get {
                return ResourceManager.GetString("MenuSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem Statement.
        /// </summary>
        internal static string MenuTask {
            get {
                return ResourceManager.GetString("MenuTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string MenuText {
            get {
                return ResourceManager.GetString("MenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string MenuUndo {
            get {
                return ResourceManager.GetString("MenuUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter code for analysis..
        /// </summary>
        internal static string MsgEnterCode {
            get {
                return ResourceManager.GetString("MsgEnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to line.
        /// </summary>
        internal static string MsgLine {
            get {
                return ResourceManager.GetString("MsgLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please create or open a file for analysis first..
        /// </summary>
        internal static string MsgOpenFirst {
            get {
                return ResourceManager.GetString("MsgOpenFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file.
        /// </summary>
        internal static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total errors: {0}.
        /// </summary>
        internal static string ParserErrorCount {
            get {
                return ResourceManager.GetString("ParserErrorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis Result.
        /// </summary>
        internal static string ParserResultTitle {
            get {
                return ResourceManager.GetString("ParserResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis completed successfully. No errors detected!.
        /// </summary>
        internal static string ParserSuccessMsg {
            get {
                return ResourceManager.GetString("ParserSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing: No errors found..
        /// </summary>
        internal static string ParserSuccessStatus {
            get {
                return ResourceManager.GetString("ParserSuccessStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to file {0}?.
        /// </summary>
        internal static string SaveConfirmMsg {
            get {
                return ResourceManager.GetString("SaveConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line: {0} | Total lines: {1}.
        /// </summary>
        internal static string StatusLineFormat {
            get {
                return ResourceManager.GetString("StatusLineFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line: {0} | Total lines: {1}.
        /// </summary>
        internal static string StatusLines {
            get {
                return ResourceManager.GetString("StatusLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis Result.
        /// </summary>
        internal static string TitleAnalysisResult {
            get {
                return ResourceManager.GetString("TitleAnalysisResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty input.
        /// </summary>
        internal static string TitleEmptyInput {
            get {
                return ResourceManager.GetString("TitleEmptyInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab not found.
        /// </summary>
        internal static string TitleTabNotFound {
            get {
                return ResourceManager.GetString("TitleTabNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assignment operator.
        /// </summary>
        internal static string TypeAssign {
            get {
                return ResourceManager.GetString("TypeAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unclosed string.
        /// </summary>
        internal static string TypeErrorString {
            get {
                return ResourceManager.GetString("TypeErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid character.
        /// </summary>
        internal static string TypeErrorSymbol {
            get {
                return ResourceManager.GetString("TypeErrorSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to identifier.
        /// </summary>
        internal static string TypeIdentifier {
            get {
                return ResourceManager.GetString("TypeIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keyword.
        /// </summary>
        internal static string TypeKeyword {
            get {
                return ResourceManager.GetString("TypeKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to semicolon.
        /// </summary>
        internal static string TypeSemicolon {
            get {
                return ResourceManager.GetString("TypeSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string constant.
        /// </summary>
        internal static string TypeString {
            get {
                return ResourceManager.GetString("TypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whitespace.
        /// </summary>
        internal static string TypeWhitespace {
            get {
                return ResourceManager.GetString("TypeWhitespace", resourceCulture);
            }
        }
    }
}
